# Generated by Django 2.2 on 2021-04-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GardeningApp', '0003_auto_20210428_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
    ]
