# Generated by Django 2.2 on 2021-04-29 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GardeningApp', '0006_comment_wall_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('message_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='GardeningApp.User')),
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='wall_message',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_comment', to='GardeningApp.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Wall_Message',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='message_comment', to='GardeningApp.Message'),
            preserve_default=False,
        ),
    ]
